version: "3.8"

services:
  app:
    build: .  # Ensures Dockerfile is used to build the image
    container_name: my-pnpm-app
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - ./pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
      - ./package.json:/usr/src/app/package.json
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
